/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrador' at '7/02/17 10:41' with Gradle 2.14.1
 *
 * 
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
